== Principles
. Make it explicit what principles are being followed
. Supply existing references, if they exist
. Architectural layering strategy
. No business logic in views
. No database access in views
. Use of interfaces
. Always use an ORM
. Dependency injection
. The Hollywood principle
. High cohesion, low coupling
. Follow SOLID
. DRY
. Ensure all components are stateless (e.g. to ease scaling)
. Prefer a rich domain model
. Prefer an anemic domain model
. Prefer stored procedures
. Avoid stored procedures
. Don't reinvent the wheel
. Approaches to error handling, logging, etc
. Buy rather than build
. Technical people only

=== Package By Feature
The desire to more easily extract features into separate services is a priority. Traditional layering strategies, such a Hexagonal Architecture, will not help in this regard. Instead, we use a packaging concept described in https://youtu.be/5OjqD-ow8GE[Modular Monoliths] and https://youtu.be/48C-RsEu0BQ[Creating a Loosely Coupled Monolith]. The main idea is that each capability of the system is partitioned into its own "slice" of the code base. We've taken the approach of using Maven modules as the primary partitioning construct. Unfortunately, Kotlin's `internal` does not work in multi-module Maven projects, so we cannot depend on the compiler in preventing cross-feature coupling. At the persistence layer, we use the same physical database host but give each module its own namespace, preventing modules from directly accessing each other's data. Lastly, we use messaging when interacting with modules, decoupling them in space and time. Only the message broker needs to be available for the system to function.